export declare const SYSTEM_ROLES: readonly [
  "SYSTEM_ADMIN",
  "RESEARCH_MANAGEMENT_HEAD",
  "RESEARCH_MANAGEMENT_STAFF",
  "LEADERSHIP_APPROVAL_AUTHORITY",
  "RESEARCH_OVERSIGHT_AUTHORITY",
  "RESEARCHER_INTERNAL_USER",
  "EXTERNAL_RESEARCHER_USER"
];

export type SystemRole = (typeof SYSTEM_ROLES)[number];
