ALTER TABLE "users" DROP CONSTRAINT "users_system_role_check";

ALTER TABLE "users" ADD CONSTRAINT "users_system_role_check"
  CHECK ("system_role" IS NULL OR "system_role" IN ('SYSTEM_ADMIN', 'SCIENTIFIC_MANAGEMENT_STAFF', 'LEADERSHIP_APPROVAL_AUTHORITY', 'RESEARCHER_INTERNAL_USER', 'EXTERNAL_RESEARCHER_USER'));
